# Generated by Django 4.0.6 on 2022-08-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
